version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - npm install -g yarn
  pre_build:
    commands:
      - echo "Installing dependencies..."
      - yarn install
  build:
    commands:
      - echo "Building the project..."
      - yarn build

artifacts:
  files:
    - '**/*'
    